# Generated by Django 6.1.1 on 2026-10-05 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        ('slots', '0002_alter_slot_options_alter_slotbooking_options_and_more'),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrtoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='centers.procurementcenter'),
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='opaque_signature',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued & Active'), ('SCANNED', 'Scanned at Gate'), ('USED', 'Used / Entry Granted'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='ISSUED', max_length=20),
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='driver_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='security_guard',
            field=models.CharField(default='Gate Operator', max_length=100),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='vehicle_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='crop_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='farmer_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='mandi_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='quantity_quintals',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='slot_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_token', to='slots.slotbooking'),
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='token_string',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
