# Generated by Django 6.1.1 on 2026-10-05 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        ('slots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['date', 'time_slot']},
        ),
        migrations.AlterModelOptions(
            name='slotbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='slots.slot'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='booked_quintals',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='farmer_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='farmer_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='mandi_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='quantity_quintals',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='token_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='vehicle_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.CheckConstraint(condition=models.Q(('booked_quintals__lte', models.F('max_capacity_quintals'))), name='slot_capacity_not_exceeded'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.CheckConstraint(condition=models.Q(('booked_quintals__gte', 0)), name='slot_booked_non_negative'),
        ),
    ]
