# Generated by Django 6.1.1 on 2026-10-05 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        ('slots', '0002_alter_slot_options_alter_slotbooking_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='idempotency_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='slotbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('farmer', 'booking_date', 'commodity'), name='unique_active_farmer_booking_date_commodity'),
        ),
    ]
