# Generated by Django 6.1.1 on 2026-10-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_farmerprofile_aadhaar_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='aadhaar_number',
        ),
    ]
