# Generated by Django 6.1 on 2026-08-27 01:59

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='12-digit UIDAI Aadhaar number validated with Verhoeff algorithm', max_length=20, null=True, validators=[common.validators.validate_aadhaar_verhoeff]),
        ),
    ]
