# Generated by Django 6.1 on 2026-08-27 01:59

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='recipient_aadhaar',
            field=models.CharField(default='9948-2019-4828', help_text='12-digit recipient Aadhaar number verified by Verhoeff checksum', max_length=20, validators=[common.validators.validate_aadhaar_verhoeff]),
        ),
    ]
