# Generated by Django 6.1.1 on 2026-10-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_recipient_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='recipient_aadhaar',
            field=models.CharField(default='XXXX-XXXX-4821', max_length=20),
        ),
    ]
